name: ntfy

services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    command: ["serve"]
    restart: unless-stopped
    init: true
    environment:
      - NTFY_BASE_URL
      - NTFY_AUTH_FILE=/var/lib/ntfy/user.db
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_CACHE_DURATION=12h
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_MAX_ATTACHMENT_SIZE=25M
      - NTFY_MAX_MESSAGE_LENGTH=4096
      - NTFY_BEHIND_PROXY=true
    #  - NTFY_ENABLE_LOGIN=true
    #  - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    volumes:
      - /data/containers/ntfy:/var/lib/ntfy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:80/v1/health >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      ingress: {}

networks:
  ingress:
    external: true
