# A sample TOML config file for SeaweedFS filer store
# Used with -config=./filer.toml

# Choose one store to enable.

####################################################
# Embed leveldb store
####################################################
[leveldb2]
enabled = true
dir = "/data/filerldb2"

