name: immich

services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    networks:
      ingress:
    volumes:
      - /data/containers/immich/library:/usr/src/app/upload:rw
      - /mnt/samsung2TB/CloudPhotos:/photos:rw
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DB_PASSWORD=${DB_PASSWORD:?Database password is required}
      - UPLOAD_LOCATION=${UPLOAD_LOCATION:-./library}
      - DB_DATA_LOCATION=${DB_DATA_LOCATION:-./postgres}
      - TZ=${TZ:-Etc/UTC}
      - IMMICH_VERSION=${IMMICH_VERSION:-release}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME:-immich}
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: 8G
    logging:
      driver: json-file
      options:
        max-size: 10m

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: unless-stopped
    networks:
      ingress:
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - DB_PASSWORD=${DB_PASSWORD:?Database password is required}
      - UPLOAD_LOCATION=${UPLOAD_LOCATION:-./library}
      - DB_DATA_LOCATION=${DB_DATA_LOCATION:-./postgres}
      - TZ=${TZ:-Etc/UTC}
      - IMMICH_VERSION=${IMMICH_VERSION:-release}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME:-immich}
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '12.00'
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: 10m

  redis:
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    container_name: immich_redis
    restart: unless-stopped
    networks:
      ingress:
    healthcheck:
      test: redis-cli ping || exit 1
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: 10m

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?Database password is required}
      - POSTGRES_DB=${DB_DATABASE_NAME:-immich}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /data/containers/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    networks:
      ingress:
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: 10m

volumes:
  model-cache:
    name: model-cache
networks:
  ingress:
    external: true