name: ai

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - WEBUI_SECRET_KEY
      - CORS_ALLOW_ORIGIN
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY
      - ENABLE_RAG_WEB_SEARCH
      - RAG_WEB_SEARCH_RESULT_COUNT
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS
      - RAG_WEB_SEARCH_ENGINE
      - GOOGLE_PSE_API_KEY
      - GOOGLE_PSE_ENGINE_ID
      - RAG_EMBEDDING_ENGINE
      - RAG_EMBEDDING_MODEL
      - RAG_TOP_K
      - RAG_OLLAMA_BASE_URL
      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333
      - QDRANT_API_KEY
    volumes:
      - /data/containers/open-webui:/app/backend/data
    devices:
      - /dev/dri:/dev/dri
    networks:
      ingress:
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--retry", "3", "--max-time", "5", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '4.00'
          memory: 4G
    logging:
      driver: json-file
      options:
        max-size: 10m

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    # ports:
    #   - "11434:11434"
    volumes:
      - /data/containers/ollama:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    networks:
      ingress: {}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '12.00'
          memory: 16G
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    # ports:
    #   - "6333:6333"
    volumes:
      - /data/containers/qdrant:/qdrant/storage
    networks:
      ingress:
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/6333'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  ingress:
    external: true