name: linkwarden

services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    container_name: linkwarden
    restart: unless-stopped
    hostname: linkwarden
    environment:
      - DATABASE_URL=postgresql://linkwarden:${DB_PASSWORD}@postgres:5432/linkwarden
      - NEXTAUTH_URL=${LINKWARDEN_URL:-https://localhost:3000}/api/v1/auth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-eC4f5sXpG1Kl4jsXZU0BjrQy4hboQQ1z}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-C9VtI8b35Cv2376AUvMHJo74K7Afdse2}
    ports:
      - 3000
    volumes:
      - /data/containers/linkwarden/data:/data/data
    depends_on:
      - meilisearch
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 64M
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      ingress:
      database:

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    container_name: meilisearch
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Dhaka}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-C9VtI8b35Cv2376AUvMHJo74K7Afdse2}
    volumes:
      - /data/containers/linkwarden/meili:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 64M
    logging:
      driver: json-file
      options:
        max-size: 10m
    networks:
      ingress:

networks:
  ingress:
    external: true
    name: ingress
  database:
    external: true
    name: database